name: CI

on:
  workflow_dispatch:
  # Temporarily disable automatic CI/CD triggers while keeping this workflow
  # available for manual runs. Retain the previous configuration for future
  # reference by commenting it out below.
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore Dissonance/Dissonance.sln

      - name: Build
        run: dotnet build Dissonance/Dissonance.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Dissonance/Dissonance.sln --configuration Release --no-build --logger trx
