name: Update Azure DevOps Work Item on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-work-item:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Extract Work Item ID from PR Body
        id: extract
        run: |
          echo "PR Body:"
          echo "${{ github.event.pull_request.body }}"
          echo "${{ github.event.pull_request.body }}" | grep -o 'AB#[0-9]*' | sed 's/AB#//' > wid.txt || true
          cat wid.txt
          wid=$(cat wid.txt)
          echo "workitem_id=$wid" >> $GITHUB_OUTPUT

      - name: Debug Work Item ID
        run: |
          echo "Extracted Work Item ID: ${{ steps.extract.outputs.workitem_id }}"

      - name: Validate GitHub Secret
        run: |
          if [ -z "${{ secrets.AZURE_DEVOPS_PAT }}" ]; then
            echo "ERROR: AZURE_DEVOPS_PAT secret is not set."
            exit 1
          else
            echo "AZURE_DEVOPS_PAT is set."
          fi

      - name: Update Azure DevOps Work Item State (Two-Step Agile Transition)
        if: ${{ steps.extract.outputs.workitem_id != '' }}
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          WORK_ITEM_ID: ${{ steps.extract.outputs.workitem_id }}
        run: |
          BASE_URL="https://dev.azure.com/DissonanceCo/Dissonance/_apis/wit/workitems/$WORK_ITEM_ID?api-version=7.0"

          echo "Step 1: Transitioning to 'Resolved'"
          response1=$(curl --write-out "%{http_code}" --silent --output response1.txt -X PATCH \
            -H "Content-Type: application/json-patch+json" \
            -H "Authorization: Basic $(echo -n :$AZURE_DEVOPS_PAT | base64)" \
            --data '[{"op": "add", "path": "/fields/System.State", "value": "Resolved"}]' \
            "$BASE_URL")

          echo "Response Code (Resolved): $response1"
          cat response1.txt

          if [ "$response1" -lt 200 ] || [ "$response1" -ge 300 ]; then
            echo "ERROR: Failed to set state to Resolved"
            exit 1
          fi

          echo "Step 2: Transitioning to 'Closed'"
          response2=$(curl --write-out "%{http_code}" --silent --output response2.txt -X PATCH \
            -H "Content-Type: application/json-patch+json" \
            -H "Authorization: Basic $(echo -n :$AZURE_DEVOPS_PAT | base64)" \
            --data '[{"op": "add", "path": "/fields/System.State", "value": "Closed"}]' \
            "$BASE_URL")

          echo "Response Code (Closed): $response2"
          cat response2.txt

          if [ "$response2" -lt 200 ] || [ "$response2" -ge 300 ]; then
            echo "ERROR: Failed to set state to Closed"
            exit 1
          fi
